config-version: 3

chat:
  format: '%s&r: %s'

messages:
  de-DE:
    prefix: '&7[&cMFXCraft&7]: &e'
    command-gamemode-changed-other: 'Du hast den Spielmodus von %s&e auf %s geändert.'
    gamemode-change: 'Dein Spielmodus wurde auf &6%s &egeändert.'
    command-godmode-changed-other-enabled: 'Du hast den God Mode von %s &caktiviert&e.'
    command-godmode-changed-other-disabled: 'Du hast den God Mode von %s &cdeaktiviert&e.'
    godmode-enabled: 'Dein God Mode ist nun &caktiviert&e.'
    godmode-disabled: 'Dein God Mode ist nun &cdeaktiviert&e.'
    command-player-only: 'Dieses Kommando ist nur für Spieler.'
    command-player-not-found: 'Dieser Spieler wurde nicht gefunden.'
    player-join: '%s &eist jetzt hier.'
    player-quit: '%s &eist jetzt weg.'
  en-US:
    prefix: '&7[&cMFXCraft&7]: &e'
    command-gamemode-changed-other: 'You changed the game mode of %s&e to %s.'
    gamemode-change: 'Your game mode was changed to &6%s&e.'
    command-godmode-changed-other-enabled: 'You &cactivated&e the god mode of %s&e.'
    command-godmode-changed-other-disabled: 'You &cdeactivated&e the god mode of %s&e.'
    godmode-enabled: 'You &cactivated&e your god mode.'
    godmode-disabled: 'You &cdeactivated&e your god mode.'
    command-player-only: 'This command is only for players.'
    command-player-not-found: 'This Player couldnt be found.'
    player-join: '%s &eis now here.'
    player-quit: '%s &eis now away.'