config-version: 5

chat:
  format: '%s&r: %s'

messages:
  de-DE:
    prefix: '&7[&cMFXCraft&7]: &e'
    gamemode-changed-other: 'Du hast den Spielmodus von %s&e auf %s geändert.'
    gamemode-changed: 'Dein Spielmodus wurde auf &6%s &egeändert.'
    godmode-enabled-other: 'Du hast den God Mode von %s &caktiviert&e.'
    godmode-disabled-other: 'Du hast den God Mode von %s &cdeaktiviert&e.'
    godmode-enabled: 'Dein God Mode ist nun &caktiviert&e.'
    godmode-disabled: 'Dein God Mode ist nun &cdeaktiviert&e.'
    fly-enabled: 'Dein Flugmodus ist nun &caktiviert&e.'
    fly-disabled: 'Dein Flugmodus ist nun &cdeaktiviert&e.'
    fly-enabled-other: 'Du hast den Flugmodus von %s &caktiviert&e.'
    fly-disabled-other: 'Du hast den Flugmodus von %s &cdeaktiviert&e.'
    spawn-teleport: 'Du wurdest zum Spawn teleportiert.'
    spawn-teleport-failed: 'Du wurdest nicht zum Spawn teleportiert.'
    command-player-only: 'Dieses Kommando ist nur für Spieler.'
    command-player-not-found: 'Dieser Spieler wurde nicht gefunden.'
    warp-list: 'Es gibt &6%d&e Warps'
    warp-teleport: 'Du wurdest zum Warp &6%s&e teleportiert.'
    warp-created: 'Du hast den Warp &6%s&e  gesetzt.'
    warp-deleted: 'Du hast den Warp &6%s&e  gelöscht.'
    warp-not-found: 'Dieser Warp konnte nicht gefunden werden'
    warp-not-permitted: 'Du bist nicht für diesen Warp berechtigt.'
    player-join: '%s &eist jetzt hier.'
    player-quit: '%s &eist jetzt weg.'
    death-suffocation: '%s &ehat es einfach nicht mehr gepackt und hat sich selbst verbuddelt.'
    death-void: '%s &eist nicht besonders bodenständig und ist ins Bodenlose gefallen.'
    death-lava: '%s &ehat einfach ein wenig zu heiß gebadet.'
    death-fall: '%s &eist hoch geflogen und sehr tief gefallen.'
    death-drowning: '%s &ewar etwas zu hydriert. Leute, #stayhydrated, aber doch nicht so viel?'
    death-fire: '%s &ehat mit dem Feuer gespielt und sich verbrannt.'
    death-starvation: '%s &everhungerte einsam und alleine in seinem Keller.'
    death-lightning: '%s &ewurde vom Zorn des Thor geblitzdingst.'
    death-poison: '%s &ehat sich an Papier geschnitten, vergiftet und ist gestorben.'
    death-wither: '%s &ehat den Wither etwas unterschätzt.'
    death-projectile: '%s &ehat einen Pfeil abbekommen. Bam, Headshot, voll ins Knie!'
    death-falling-block: '%s &eist der Himmel auf den Kopf gefallen.'
    death-magic: '%s &ehat sich mit den mystischen Mächten angelegt und verloren.'
    death-suicide: '%s &ehat sich entschieden, dass das Leben nichts mehr wert ist.'
    death-thorns: '%s &ehat sich an einer Dorne gesprochen.'
    death-cramming: '%s &ehat den Mund etwas zu voll genommen.'
    death-dragon-breath: '%s &emusste dich dem Mundgeruch eines Drachen geschlagen geben.'
    death-custom: '%s &eweilt nicht mehr unter uns.'
    death-dryout: '%s &eist ausgetrocknet.'
    death-hot-floor: '%s &ehat die heiße Kartoffel gegessen.'
    death-fly-into-wall: '%s &ehat sein Leben vor die Wand gesetzt.'
    death-melting: '%s &eist dahingeschmolzen.'
    death-fire-tick: '%s &ehat mit dem Feuer gespielt und sich verbrannt.'
    death-contact: '%s &ewurde es auf der Welt zu eng.'
    death-entity-explosion: '%s &ewurde mit einer Rakete auf den Mars geschossen.'
    death-block-explosion: '%s &ewurde mit einer Rakete auf den Mars geschossen.'
    death-entity-attack: '%s &ewurde von &r%s &ezu hart angefasst.'
    death-entity-sweep-attack: '%s &ewurde von &r%s &ezu hart angefasst.'
  en-US:
    prefix: '&7[&cMFXCraft&7]: &e'
    gamemode-changed-other: 'You changed the game mode of %s&e to %s.'
    gamemode-changed: 'Your game mode was changed to &6%s&e.'
    godmode-enabled-other: 'You &cactivated&e the god mode of %s&e.'
    godmode-disabled-other: 'You &cdeactivated&e the god mode of %s&e.'
    godmode-enabled: 'You &cactivated&e your god mode.'
    godmode-disabled: 'You &cdeactivated&e your god mode.'
    fly-enabled: 'You &cactivated&e your flight mode.'
    fly-disabled: 'You &cdeactivated&e your flight mode.'
    fly-enabled-other: 'You &cactivated&e the god mode of %s&e.'
    fly-disabled-other: 'You &cdeactivated&e the god mode of %s&e.'
    spawn-teleport: 'You have been teleported to the spawn.'
    spawn-teleport-failed: 'You have not been teleported to the spawn.'
    command-player-only: 'This command is only for players.'
    command-player-not-found: 'This Player couldnt be found.'
    player-join: '%s &eis now here.'
    player-quit: '%s &eis now away.'