name: Crucio
main: com.mysteryworlds.crucio.CrucioApp
version: 1.1.0-SNAPSHOT

author: Felix Klauke

website: https://www.mysteryworlds.com

api-version: 1.15

depend:
  - Vault
  - ProtocolLib

commands:
  gamemode:
    description: Changes your own or other players game mode.
    aliases:
      - gm
      - mode
    permission: crucio.command.gamemode
  godmode:
    description: Changes your own or other players god mode.
    aliases:
      - god
    permission: crucio.command.godmode
  fly:
    description: Changes you fly mode
    permission: crucio.command.fly
  spawn:
    description: Teleports you to the worlds spawn
    permission: crucio.command.spawn
  warp:
    description: Teleports you to certain positions
    permission: crucio.command.warp

permissions:
  crucio.*:
    description: "Gives you access to all of crucio"
    default: op
    children:
      - crucio.command.*
  crucio.command.*:
    description: "Gives you access to all crucio commands"
    default: op
    children:
      - crucio.command.gamemode.*
      - crucio.command.godmode.*
      - crucio.command.fly.*
      - crucio.command.spawn
      - crucio.command.warp.*
  crucio.command.gamemode.*:
    description: "Gives you access to all game mode related commands"
    children:
      - crucio.command.gamemode
      - crucio.command.gamemode.other
  crucio.command.gamemode:
    description: "Gives you access for the command to change your game mode"
  crucio.command.gamemode.other:
    description: "Gives you access for the command to change other players game mode"
  crucio.command.godmode.*:
    description: "Gives you access to all god mode related commands"
    children:
      - crucio.command.godmode
      - crucio.command.godmode.other
  crucio.command.godmode:
    description: "Gives you access for the command to change your god mode"
  crucio.command.godmodeother:
    description: "Gives you access for the command to change other players god mode"
  crucio.command.fly.*:
    description: "Gives you access to all fly related commands"
    children:
      - crucio.command.fly
      - crucio.command.fly.other
  crucio.command.fly:
    description: "Gives you access for the command to change your fly mode"
  crucio.command.fly.other:
    description: "Gives you access for the command to change other players fly mode"
  crucio.command.spawn:
    description: "Gives you access for teleporting to the spawn"
  crucio.command.warp.*:
    description: "Gives you access to all warp commands"
    children:
      - crucio.command.warp
      - crucio.command.warp.list
      - crucio.command.warp.create
      - crucio.command.warp.delete
      - crucio.warp.all
  crucio.command.warp:
    description: "Gives you access for the command to warp to positions"
  crucio.command.warp.list:
    description: "Gives you access for the command to list all warps"
  crucio.command.warp.create:
    description: "Gives you access for the command to create warps"
  crucio.command.warp.delete:
    description: "Gives you access for the command to delete warps"
  crucio.warp.all:
    description: "Gices you access to every single warp point"